#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     gyro,           sensorAnalogInactive)
#pragma config(Sensor, S3,     IRSEEK,         sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     TOUCHMUX,           sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     ELEVATOR,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ARM,           tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVEFL,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVEFR,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     DRIVEBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     DRIVEBR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    grab_servoL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    grab_servoR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    ring_servo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//WRECKER ROBOTICS TELE-OP PROGRAM || AUTHORS: MAX LIBEN + ALEC SOLDER || DATE: APRIL 16TH, 2013 ||
//DESCRIPTION: Designed for two controllers. Handles manual control as well as preset positions. Function definitions can be found in "references4.h".
//Preset positions utilize encoders to move elevator and arm to their correct scoring positions while maintaining the ability to drive the robot.

//UP ENCODER VALUES ARE NEGATIVE


#include "references4.h"
#include "advjoystickdriver1.h"  //Include file to "handle" the Bluetooth messages.

//############################################################################################INITIALIZING ROBOT PROCDURE
void initializeRobot()//Define initialize function Initialize robot into everything down position Grabber flat against arm
{
	servo[grab_servoL] = 0;
	servo[grab_servoR] = 255;
	servo[ring_servo] = 255;
	nMotorEncoder[ARM] = 0;
	nMotorEncoder[ELEVATOR] = 0;
  initJoystick();
  return;
}
//#######################################################################################################################
//#####################################################################################################TELEOP ACTUAL CODE
task main()
{
	initializeRobot();//Initialize robot
  waitForStart();// wait for start of tele-op phase

//##########################################################################################INITIALLY ESTABLISH VARIABLES
	int y = 0;//Value to regulate speed of manual grabber adjusting
	int positionSet = 0;//Setting manual control (to start)
	int initialElevatorPosition;//Defining Elevator position variable
	int initialArmPosition;//Defining Arm position variable
	bool elevatorSet = false;
	bool armSet = false;
//#######################################################################################################################
while(true)
	{
	updateJoystick();//Check for joystick buttons all the time
//##############################################################################################RESET WHEN BUTTON PRESSED
		if(SensorValue(TOUCHMUX) & mux_button4){ //ARM RESET
			nMotorEncoder[ARM] = 0;
		}
		if(SensorValue(TOUCHMUX) & mux_button3){ //ELEVATOR RESET
			nMotorEncoder[ELEVATOR] = 0;
		}
//########################################################################################################################
//######################################################################################################PID CONTROL ENABLE
		if(joy1Hold(4)){
			nMotorPIDSpeedCtrl[DRIVEFL] = mtrSpeedReg;
			nMotorPIDSpeedCtrl[DRIVEFR] = mtrSpeedReg;
		}
		else{
			nMotorPIDSpeedCtrl[DRIVEFL] = mtrNoReg;
			nMotorPIDSpeedCtrl[DRIVEFR] = mtrNoReg;
		}
//#######################################################################################################################
//################################################################################################BASIC ELEVATOR COMMANDS
		if (joy1Hold(6)){//Elevator up
				positionSet = 0;//Manual control ENGAGED (so it can over-ride commands)
				elevatorUp();
										}
		else if (joy1Hold(8)){//Elevator down w/ floor in there (encoder reads negetive as it goes up
				positionSet = 0;

			if(SensorValue(TOUCHMUX) & mux_button3){
				stopE();
			}
			else{
				elevatorDown();
			}
		}
		else if (positionSet == 0){
			stopE();
		}
//#######################################################################################################################
//##############################################################################################BASIC ARM COMMANDS + SLOW
		if(joy1Hold(5) && joy1Hold(4) && nMotorEncoder[ARM] > -3500){//Move arm slowly upwards if 4 is also being held while holding the arm upwards button w/ ceiling
			positionSet = 0;
			armUpSlow();
		}

		else if(joy1Hold(5) && nMotorEncoder[ARM] > -3500){//Move arm upwards regular 100% speed w/ ceiling
			positionSet = 0;
			armUp();
		}

		else if(joy1Hold(7) && joy1Hold(4)){ //&& nMotorEncoder[ARM] < -60){//Move arm downwards if 4 is also being held while holding the arm downwards button w/ floor
			positionSet = 0;

			if(SensorValue(TOUCHMUX) & mux_button4){
				stopA();
			}
			else{
			armDownSlow();
			}
		}

		else if(joy1Hold(7)){ //&& nMotorEncoder[ARM] < -60){//Move arm downwards regular 100% speed w/ floor
			positionSet = 0;
			if(SensorValue(TOUCHMUX) & mux_button4){
				stopA();
			}
			else{
				armDown();
			}
		}

		else if(positionSet == 0){//If not holding arm control buttons, arm stops (but only if in manual control)
			if(positionSet == 0){
				stopA();
			}
		}
//#######################################################################################################################
//###################################################################################################HATCH MANUAL CONTROL
		if(joy2Hold(5)){//Open hatch
			servo[ring_servo] = 0;
		}

		if(joy2Hold(7)){//Close hatch
			servo[ring_servo] = 255;
		}
//#######################################################################################################################
//#############################################################################SETTING ENCODER VARIABLES = ENCODER VALUES
		if(positionSet == 0){//When in manual control, you're setting the variables used in the automatic position buttons to current values
			initialElevatorPosition = nMotorEncoder[ELEVATOR];
			initialArmPosition = nMotorEncoder[ARM];
		}
//#######################################################################################################################
//#########################################################################################POSITION PRESET BUTTON CONTROL
		if(joy2Hold(1)){//Setting the desired position of the robot: Grab rings. Servos are set in their while arm and elevator are moving position
			positionSet = 1;
			elevatorSet = false;
			armSet = false;
			servo[grab_servoL] = 0;
			servo[grab_servoR] = 255;
			servo[ring_servo] = 0;
		}

		if(joy2Hold(2)){//Setting the desired position of the robot: Lowest rung. Servos are set in its while arm and elevator are moving position
			positionSet = 2;
			elevatorSet = false;
			armSet = false;
			//servo[ring_servo] = 255;
		}

		if(joy2Hold(3)){//Setting the desired position of the robot: Middle rung. Servos are set in its while arm and elevator are moving position
			positionSet = 3;
			elevatorSet = false;
			armSet = false;
			servo[ring_servo] = 255;
		}

		if(joy2Hold(4)){//Setting the desired position of the robot: Top rung. Servos are set in their while arm and elevator are moving position
			positionSet = 4;
			servo[grab_servoL] = 122;
			servo[grab_servoR] = 133;
			elevatorSet = false;
			armSet = false;
			servo[ring_servo] = 255;
		}

		if(joy2Hold(6)){//Setting the desired position of the robot: SCOOP. Servos are set in their while arm and elevator are moving position
			positionSet = 5;
			elevatorSet = false;
			armSet = false;
			servo[grab_servoL] = 110;
			servo[grab_servoR] = 145;
			servo[ring_servo] = 0;
		}

		if(joy2Hold(8)){//Setting the desired position of the robot: SCOOP. Servos are set in their while arm and elevator are moving position
			positionSet = 6;
			elevatorSet = false;
			armSet = false;
			servo[grab_servoL] = 0;
			servo[grab_servoR] = 255;
		}
//#######################################################################################################################
//##########################################################################################ESTABLISHING PRESET POSITIONS
		if(positionSet == 1){//Telling where the arm and elevator should go in position "position1". Arm is all the way down, elevator is slightly up. Grabber is already flat against arm
			if(nMotorEncoder[ELEVATOR] > -2750 && initialElevatorPosition > -2750){ //NUMBER for height to get rings
				elevatorUp();
			}
			else if(nMotorEncoder[ELEVATOR] < -2750 && initialElevatorPosition < -2750){ //NUMBER for height to get rings
				elevatorDown();
			}
			else{
				stopE();
				elevatorSet = true; //on target
			}
			if(SensorValue(TOUCHMUX) & mux_button4){ //&& nMotorEncoder[ARM] < -100){
				stopA();
				armSet = true; //on target
			}
			else{
				armDown();
			}
			if(elevatorSet == true && armSet == true){
				positionSet = 0;
			}
		}

		if(positionSet == 2){//Telling where the arm and elevator should go in position "position2". Arm is going horizontal-ish, elevator is all the way down. After arm and elevator move, it tells grabber to go to scoring position for 1st height
			if(nMotorEncoder[ELEVATOR] < -550 && initialElevatorPosition < -550){ //NUMBER for bottom post height
				elevatorDown();
			}
			else if(nMotorEncoder[ELEVATOR] > -550 && initialElevatorPosition > -550){ //NUMBER for bottom post height
				elevatorUp();
			}
			else{
				stopE();
				elevatorSet = true; //on target
			}
			if(nMotorEncoder[ARM] < -2000 && initialArmPosition < -2000){ //NUMBER for arm scoring angle
				armDown();
			}
			else if(nMotorEncoder[ARM] > -2000 && initialArmPosition > -2000){ //NUMBER for arm scoring angle
				armUp();
			}
			else{
				stopA();
				armSet = true; //on target
			}
			if(elevatorSet == true && armSet == true){
				servo[grab_servoL] = 202;  //NUMBER
				servo[grab_servoR] = 53;  //NUMBER
				positionSet = 0;
			}
		}

		if(positionSet == 3){//Telling where the arm and elevator should go in position "position3". Arm is going horizontal-ish, elevator is up a bunch. After arm and elevator move, it tells grabber to go to scoring position for 2nd height
			if(nMotorEncoder[ELEVATOR] > -7850 && initialElevatorPosition > -7850){ //NUMBER for middle post height
				elevatorUp();
			}
			else if(nMotorEncoder[ELEVATOR] < -7850 && initialElevatorPosition < -7850){ //NUMBER for middle post height
				elevatorDown();
			}
			else{
				stopE();
				elevatorSet = true; //on target
			}

			if(nMotorEncoder[ARM] < -1800 && initialArmPosition < -1800){ //NUMBER for arm scoring angle
				armDown();
			}
			else if(nMotorEncoder[ARM] > -1800 && initialArmPosition > -1800){ //NUMBER for arm scoring angle
				armUp();
			}
			else{
				stopA();
				armSet = true; //on target
			}
			if(elevatorSet == true && armSet == true){
				servo[grab_servoL] = 192;  //NUMBER
				servo[grab_servoR] = 63;  //NUMBER
				positionSet = 0;
			}
		}

		if(positionSet == 4){//Telling where the arm and elevator should go in position "position4". Arm is going slightly higher than horizonatal, elevator is at max height. After arm and elevator move, it tells grabber to go to scoring position for 3nd height
			if(nMotorEncoder[ELEVATOR] > -11200 && initialElevatorPosition > -11200){ //NUMBER for top post height
				elevatorUp();
			}
			else if(nMotorEncoder[ELEVATOR] < -11200 && initialElevatorPosition < -11200){ //NUMBER for top post height
				elevatorDown();
			}
			else{
				stopE();
				elevatorSet = true; //on target
			}

			if(nMotorEncoder[ARM] > -3050 && initialArmPosition > -3050){//NUMBER for arm scoring angle
				armUp();
			}
			else if(nMotorEncoder[ARM] < -3050 && initialArmPosition < -3050){ //NUMBER for arm scoring angle
				armDown();
			}
			else{
				stopA();
				armSet = true; //on target
			}
			if(elevatorSet == true && armSet == true){
				servo[grab_servoL] = 255;  //NUMBER
				servo[grab_servoR] = 0;  //NUMBER
			positionSet = 0;
			}
		}

		if(positionSet == 5){//Telling where the arm and elevator should go in position "position5". Arm is going a little bit out, elevator is at the bottom. Grabber is already at scoop position
			if(SensorValue(TOUCHMUX) & mux_button3){ //NUMBER for height to get rings
				stopE();
				elevatorSet = true;
			}
			else{
				elevatorDown();
			}
			if(nMotorEncoder[ARM] < -825 && initialArmPosition < -825){
				armDown();
			}
			else if(nMotorEncoder[ARM] > -825 && initialArmPosition > -825){
				armUp();
			}
			else{
				stopA();
				armSet = true; //on target
			}
			if(elevatorSet == true && armSet == true){
					servo[grab_servoL] = 115;  //NUMBER
				servo[grab_servoR] = 140;  //NUMBER
				positionSet = 0;
			}
		}

		if(positionSet == 6){//Telling where the arm and elevator should go in position "position1". Arm is all the way down, elevator is slightly up. Grabber is already flat against arm
			if(SensorValue(TOUCHMUX) & mux_button3){
				stopE();
				elevatorSet = true;
			}
			else{
				elevatorDown();
			}
			if(SensorValue(TOUCHMUX) & mux_button4){ //&& nMotorEncoder[ARM] < -100){
				stopA();
				armSet = true;
			}
			else{
				armDown();
			}
			if(elevatorSet == true && armSet == true){
				positionSet = 0;
			}
		}
//#######################################################################################################################
//###########################################################################################MANUAL GRABBER SERVO CONTROL
		if(joy1Hold(1)){//move grabber one direction 10 degrees, integer y in there so it doesn't adjust 10 per run through the while loop
			if(y == 0){
				servo[grab_servoL] += 10;
				servo[grab_servoR] -= 10;
				y = 1;
			}
		}

		else if(joy1Hold(3)){//move grabber one direction 10 degrees, integer y in there so it doesn't adjust 10 per run through the while loop
			if(y == 0){
				servo[grab_servoL] -= 10;
				servo[grab_servoR] += 10;
				y = 1;
			}
		}
		else{
			y = 0;
		}
//#######################################################################################################################
//###############################################################################################MOVEMENT CONTROL W/ SLOW
	if(joy1.hat != kHatCentered && joy1Hold(4)){//If a directional button is pressed, and 4 is held, go into this loop where driving is super slow

	 	if(joy1.hat == kHatUp){//ForwardSlow
	    driveForwardSuperSlow();
		}

	  if(joy1.hat == kHatDown){//BackwardSlow
	    	driveBackSuperSlow();
	  }

	  if(joy1.hat == kHatLeft){//LeftSlow
	    	driveLeftSuperSlow();
		}

    if(joy1.hat == kHatRight){//RightSlow
	    	driveRightSuperSlow();
	  }
	}
	else if (joy1.hat != kHatCentered){//If a directional button is pressed, go into this loop where driving happens

	 	if(joy1.hat == kHatUp){//Forward
	    driveForward();
		}

	  if(joy1.hat == kHatDown){//Down
	    	driveBack();
	  }

	  if(joy1.hat == kHatLeft){//Left
	    	driveLeft();
		}

    if(joy1.hat == kHatRight){//Right
	    	driveRight();
	  }
	}

	else if(joy1.hat == kHatCentered){//If a directional button is not pressed, don't move drive motors
	 stopM();
	}
//######################################################################################################################
//######################################################################################################################
}
}
